# Generated by Django 5.2.17 on 2026-09-07 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Session ID')),
                ('hr_name', models.CharField(blank=True, max_length=120, verbose_name='Recruiter name')),
                ('hr_email', models.EmailField(blank=True, max_length=254, verbose_name='Recruiter email')),
                ('company_name', models.CharField(blank=True, max_length=160, verbose_name='Company name')),
                ('interview_requested', models.BooleanField(default=False, help_text='True once the recruiter has asked to schedule an interview.', verbose_name='Interview requested')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Last active')),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Barkley (assistant)')], max_length=16, verbose_name='Sender')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
