# Generated by Django 5.2.17 on 2026-09-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('profile', 'Career profile'), ('github_readme', 'GitHub README')], default='profile', max_length=32, verbose_name='Kind')),
                ('source', models.CharField(help_text="owner/repo for READMEs, 'profile' for the local career profile.", max_length=200, verbose_name='Source')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('default_branch', models.CharField(blank=True, max_length=100, verbose_name='Default branch')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Content hash')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Last fetched')),
            ],
            options={
                'ordering': ['kind', 'source'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'source'), name='uniq_knowledge_kind_source')],
            },
        ),
    ]
