# Generated by Django 5.2.17 on 2026-09-12 15:30

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_knowledgedocument'),
    ]

    operations = [
        # Enables the pgvector extension on PostgreSQL (a no-op elsewhere), so
        # the VectorField below can be created on a fresh database.
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(verbose_name='Ordinal')),
                ('content', models.TextField(verbose_name='Content')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='Tokens')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='Content hash')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, null=True, verbose_name='Embedding')),
                ('indexed_at', models.DateTimeField(auto_now=True, verbose_name='Indexed at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chat.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'ordinal'],
                'constraints': [models.UniqueConstraint(fields=('document', 'ordinal'), name='uniq_chunk_document_ordinal')],
            },
        ),
    ]
