# Generated by Django 5.2.17 on 2026-09-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_knowledgechunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_name', models.CharField(blank=True, max_length=120, verbose_name='Recruiter name')),
                ('hr_email', models.EmailField(blank=True, max_length=254, verbose_name='Recruiter email')),
                ('company_name', models.CharField(blank=True, max_length=160, verbose_name='Company name')),
                ('message', models.TextField(blank=True, help_text='The recruiter message that made BarklAI flag the interview.', verbose_name='Triggering message')),
                ('language', models.CharField(blank=True, max_length=8, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('notified_at', models.DateTimeField(blank=True, help_text='When the notification email reached Andrea (NULL = still pending).', null=True, verbose_name='Notified at')),
                ('notification_error', models.CharField(blank=True, max_length=255, verbose_name='Notification error')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to='chat.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
