# Generated by Django 5.2.17 on 2026-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_interviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='Knowledge-base labels BarklAI cited for this reply (always empty on a user turn).', verbose_name='Cited sources'),
        ),
    ]
